name: flutter_movie_ticket
description: A Flutter Movie App.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Optional dependency
  lottie: ^1.2.2
  device_preview: ^1.1.0
  appinio_swiper: ^2.0.0
  http: ^0.13.5
  dropdown_search: ^5.0.6
  url_launcher: ^6.1.11
  share_plus: ^7.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/lotties/
    - assets/logos/

  uses-material-design: true
