// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiWcJzKwtTiyR4nX7wPJwHdlvqrF8aCLY',
    appId: '1:510414475078:web:a02ac12ba3378641fddf47',
    messagingSenderId: '510414475078',
    projectId: 'flixer-fd9d5',
    authDomain: 'flixer-fd9d5.firebaseapp.com',
    storageBucket: 'flixer-fd9d5.appspot.com',
    measurementId: 'G-6TVNSGGFWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBldcESdzAUzFyLgOVVPCZZdMN1fPaVobA',
    appId: '1:510414475078:android:aef179688b192624fddf47',
    messagingSenderId: '510414475078',
    projectId: 'flixer-fd9d5',
    storageBucket: 'flixer-fd9d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhWUC-HAkiGBYpkM1UuA51Q2Y7P01d_Ms',
    appId: '1:510414475078:ios:2fc971a28b87e280fddf47',
    messagingSenderId: '510414475078',
    projectId: 'flixer-fd9d5',
    storageBucket: 'flixer-fd9d5.appspot.com',
    iosClientId: '510414475078-di7l6b2hq25t40rcuha7e3be45prg96s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMovieMatchUSM',
  );
}
